/** Existing utility names map to the shared orange/slate theme tokens in index.css. */
const color = name => `rgb(var(--${name}) / <alpha-value>)`;
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: { extend: { colors: {
    "surface": color("background"),
    "surface-dim": color("background"),
    "surface-bright": color("surface-hover"),
    "surface-container-lowest": color("surface"),
    "surface-container-low": color("surface-secondary"),
    "surface-container": color("surface"),
    "surface-container-high": color("surface-secondary"),
    "surface-container-highest": color("surface-hover"),
    "on-surface": color("text-primary"),
    "on-surface-variant": color("text-secondary"),
    "inverse-surface": color("text-primary"),
    "inverse-on-surface": color("surface"),
    "outline": color("text-muted"),
    "outline-variant": color("border"),
    "surface-tint": color("primary"),
    "primary": color("primary"),
    "on-primary": color("on-primary"),
    "primary-container": color("primary-soft"),
    "on-primary-container": color("primary"),
    "inverse-primary": color("primary"),
    "secondary": color("primary"),
    "on-secondary": color("on-primary"),
    "secondary-container": color("primary-soft"),
    "on-secondary-container": color("primary"),
    "tertiary": color("accent"),
    "on-tertiary": color("on-primary"),
    "tertiary-container": color("accent-soft"),
    "on-tertiary-container": color("text-primary"),
    "error": color("danger"),
    "on-error": color("on-primary"),
    "error-container": color("danger-soft"),
    "on-error-container": color("danger"),
    "border": color("border"),
    "accent": color("accent"),
    "brand-highlight": color("brand-highlight"),
    "fresh": color("fresh"), "fresh-soft": color("fresh-soft"),
    "sky": color("sky"), "sky-soft": color("sky-soft"),
    "success": color("success"),
    "warning": color("warning"),
  }, boxShadow: { soft: "0 4px 18px rgb(15 23 42 / 0.07)" } } },
  plugins: [],
};
