"""Small identity vocabulary, not a nutrient database or product safety certificate.

Only exact whole-food aliases establish a composition category. Unknown composites,
brands, and qualifiers are intentionally unresolved. No numeric nutrition is stored here.
"""
from dataclasses import dataclass
import re
import json
from pathlib import Path


@dataclass(frozen=True)
class IngredientIdentity:
    name: str
    aliases: tuple[str, ...]
    category: str = 'plant'
    allergens: tuple[str, ...] = ()


IDENTITIES = [
    IngredientIdentity('olive oil', ('olive oil', 'extra virgin olive oil', 'oil olive salad or cooking')),
    IngredientIdentity('chicken breast', ('chicken breast', 'chicken breasts'), 'meat'),
    IngredientIdentity('beef', ('beef', 'ground beef'), 'meat'),
    IngredientIdentity('salmon', ('salmon',), 'fish', ('fish',)),
    IngredientIdentity('shrimp', ('shrimp', 'prawns'), 'shellfish', ('shellfish',)),
    IngredientIdentity('egg', ('egg', 'eggs'), 'egg', ('eggs',)),
    IngredientIdentity('milk', ('milk',), 'dairy', ('milk',)),
    IngredientIdentity('greek yogurt', ('greek yogurt', 'greek yoghurt'), 'dairy', ('milk',)),
    IngredientIdentity('yogurt', ('yogurt', 'yoghurt'), 'dairy', ('milk',)),
    IngredientIdentity('butter', ('butter',), 'dairy', ('milk',)),
    IngredientIdentity('cheese', ('cheese',), 'dairy', ('milk',)),
    IngredientIdentity('tofu', ('tofu',), 'plant', ('soy',)),
    IngredientIdentity('peanut', ('peanut', 'peanuts', 'peanut butter'), 'plant', ('peanuts',)),
    IngredientIdentity('almond', ('almond', 'almonds'), 'plant', ('tree nuts',)),
    IngredientIdentity('walnut', ('walnut', 'walnuts'), 'plant', ('tree nuts',)),
    IngredientIdentity('sesame', ('sesame', 'sesame seeds', 'tahini'), 'plant', ('sesame',)),
    IngredientIdentity('wheat flour', ('wheat flour', 'all purpose flour'), 'plant', ('wheat', 'gluten')),
    IngredientIdentity('honey', ('honey',), 'honey'),
    *[IngredientIdentity(name, aliases) for name, aliases in [
        ('lentil', ('lentil', 'lentils')), ('chickpea', ('chickpea', 'chickpeas', 'garbanzo beans')),
        ('black bean', ('black bean', 'black beans')), ('brown rice', ('brown rice',)),
        ('white rice', ('white rice',)), ('quinoa', ('quinoa',)),
        ('broccoli', ('broccoli',)), ('spinach', ('spinach',)), ('tomato', ('tomato', 'tomatoes')),
        ('onion', ('onion', 'onions')), ('garlic', ('garlic',)), ('carrot', ('carrot', 'carrots')),
        ('zucchini', ('zucchini', 'courgette')), ('mushroom', ('mushroom', 'mushrooms')),
        ('apple', ('apple', 'apples')), ('banana', ('banana', 'bananas')), ('avocado', ('avocado', 'avocados')),
        ('basil', ('basil',)), ('oregano', ('oregano',)), ('cumin', ('cumin',)), ('paprika', ('paprika',)),
        ('salt', ('salt', 'table salt')), ('water', ('water',)),
    ]],
]


def clean_name(value: str) -> str:
    return ' '.join(re.sub(r'[^a-z0-9]+', ' ', value.casefold()).split())


ALIASES = {clean_name(alias): item for item in IDENTITIES for alias in item.aliases}

# Authoritative discovery data; frontend copy is generated by sync_ingredient_catalog.py.
# Search aliases are not blanket composition or substitution equivalences.
DISCOVERY = json.loads(Path(__file__).with_name('ingredient_discovery.json').read_text(encoding='utf-8'))
DISCOVERY_ALIASES = {clean_name(alias): item for item in DISCOVERY
                     for alias in [item['name'], item['canonical'], *item['aliases']]}
for item in DISCOVERY:
    if item['composition'] is None:
        continue  # Composite names are discoverable without asserting their composition.
    identity = next((x for x in IDENTITIES if x.name == item['canonical']), None)
    if identity is None and item['canonical'] not in ALIASES:
        identity = IngredientIdentity(item['canonical'], tuple(item['aliases']),
                                      item['composition'], tuple(item['allergens']))
        IDENTITIES.append(identity)
    if identity:
        for alias in item['aliases']:
            ALIASES.setdefault(clean_name(alias), identity)


def related_identity(left: str, right: str) -> bool:
    """Explicit direct parent/child relation means uncertain relevance, never HAVE."""
    a, b = DISCOVERY_ALIASES.get(left), DISCOVERY_ALIASES.get(right)
    return bool(a and b and (a['parent'] == b['canonical'] or b['parent'] == a['canonical']))


def search_ingredients(query: str, limit: int = 10) -> list[dict]:
    query = clean_name(query)
    if not query:
        return []
    def rank(item):
        names = [clean_name(item['name']), clean_name(item['canonical'])]
        aliases = [clean_name(x) for x in item['aliases']]
        checks = [query in names, query in aliases,
                  any(x.startswith(query) for x in names), any(x.startswith(query) for x in aliases),
                  any(query in x for x in names), any(query in x for x in aliases)]
        return next((i for i, match in enumerate(checks) if match), 6)
    return sorted((x for x in DISCOVERY if rank(x) < 6),
                  key=lambda x: (rank(x), clean_name(x['name']), x['id']))[:limit]


def identity_for(name: str) -> IngredientIdentity | None:
    return ALIASES.get(clean_name(name))
